### ISSUE TITLE
can i send data to segment directly without use firebase dependency

### ISSUE THREAD

**Issue by mohamedebrahim96** [segment-integrations/analytics-android-integration-firebase#14]
can i send data to segment directly and after that send it to firebase

i mean without using this dependency 
`compile 'com.segment.analytics.android.integrations:firebase:+'`

**Comment by prayansh** [comment]
You can use the firebase integration in [cloud mode](https://segment.com/docs/connections/destinations/#connection-modes) for this. That will allow you to send events to Segment, who will then route it to Firebase on the server-side
