### ISSUE TITLE
Firebase events

### ISSUE THREAD

**Issue by mirsaidoff** [segment-integrations/analytics-android-integration-firebase#16]
I am wondering why firebase is sometimes not working (or working but not on real-time view). I am sending events, but when I look at firebase stream view, there is no data. Even after an hour (or half). But, sometimes I notice there (on firebase) are events have been recorded. Is it an issue? Or It takes so much time for you to send and for firebase to recieve the data?

**Comment by alanjcharles** [comment]
Hi @mirsaidoff ! Firebase can take up to 24 hours to populate dashboards with your event data. If you want to quickly validate your implementation, I would recommend using [Firebase's DebugView](https://firebase.google.com/docs/analytics/debugview) functionality. This will show you a stream of "real-time" events in your Firebase instance and it's relatively straightforward to implement. 

I hope this helps! If you're running into any issues with your Segment <> Firebase integration, I would recommend reaching out to friends@segment.com. They can help you validate your implementation and escalate bugs as necessary. Good luck!
