### ISSUE TITLE
SDK v2.3.1 - Still getting NullPointerException on products iterator

### ISSUE THREAD

**Issue by FrancescoRigoni** [segment-integrations/analytics-android-integration-firebase#40]
I upgraded my SDK to version 2.3.1 because of this [fix](https://github.com/segment-integrations/analytics-android-integration-firebase/pull/39/files).

However after releasing a new version of my app I still see the NullPointerException on products.
Here is the full stack trace.

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

com.segment.analytics.android.integrations.firebase.FirebaseIntegration.formatProducts (FirebaseIntegration.java:227)
com.segment.analytics.android.integrations.firebase.FirebaseIntegration.formatProperties (FirebaseIntegration.java:216)
com.segment.analytics.android.integrations.firebase.FirebaseIntegration.track (FirebaseIntegration.java:186)
com.segment.analytics.IntegrationOperation$10.run (IntegrationOperation.java:205)
com.segment.analytics.Analytics.performRun (Analytics.java:1464)
com.segment.analytics.Analytics$10.run (Analytics.java:825)
```

Is this still an issue or is there something else I have to do besides upgrading?

**Comment by wenxi-zeng** [comment]
a fix is made. ready for the next release. will come back and close this issue once the release is out.

**Comment by wenxi-zeng** [comment]
2.3.2 is out. closing this ticket. feel free to reopen if the issue still persists

**Comment by FrancescoRigoni** [comment]
Thank you!
