### ISSUE TITLE
Loading dependency stopped working

### ISSUE THREAD

**Issue by michal-chojnacki** [segment-integrations/analytics-android-integration-firebase#46]
Today i've noticed that loading dependency stopped working. I have it defined in my project as:
`implementation 'com.segment.analytics.android.integrations:firebase:+@aar'`.

Until today it work properly, however right now I'm getting the error:
``` > Failed to list versions for com.segment.analytics.android.integrations:firebase.
> Unable to load Maven meta-data from https://jcenter.bintray.com/com/segment/analytics/android/integrations/firebase/maven-metadata.xml.
 > Could not HEAD 'https://jcenter.bintray.com/com/segment/analytics/android/integrations/firebase/maven-metadata.xml'.
  > Read timed out
```

**Comment by Jbwzx** [comment]
Having the same issue

**Comment by mfs-ariel-rios** [comment]
Me too! :/

**Comment by Jbwzx** [comment]
For anyone needing quick fix, feel free to replace integration dependency with explicit one:
`implementation 'com.segment.analytics.android.integrations:firebase:2.3.3@aar'`
